# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'AutocompleteDemo' do
pod 'Autocomplete', :path => '../'
end

target 'AutocompleteDemoTests' do

end

